### Get Pokemon info
GET http://localhost:1234/pokemon/ditto

### Get 404
GET http://localhost:1234/pokemon


### Create a Pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json
{
  "name": "ditto",
  "type": "normal",
  "moves": [
      "transform"
  ]
}
