### Get
GET http://localhost:1234/

### Get Pokemon info
GET http://localhost:1234/pokemon/ditto

### Get 404
GET http://localhost:1234/pokemon

### Create a Pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
      "transform"
  ]
}

### Get movies
GET http://localhost:1234/movies

### Get movies filtered by Genre
GET http://localhost:1234/movies?genre=action

### Get a movie
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Create a movie
POST http://localhost:1234/movies
Content-Type: application/json
{
  "title": "The Goodfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]

}